#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

spring:
  jpa:
    hibernate:
      ddl-auto: none # Вимикаємо автооновлення схеми на старті, щоб Hibernate не чіпав БД
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # Вимикаємо отримання метаданих через підключення на старті
        temp:
          use_jdbc_metadata_defaults: false

tenants:
  default_db:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1111
  tasks_db:
    url: jdbc:postgresql://localhost:5432/tasks_db
    username: postgres
    password: tasks
  coffee_db:
    url: jdbc:postgresql://localhost:5432/coffee_db
    username: postgres
    password: coffee